# Podfile Final e Corrigido
platform :ios, '14.0'
use_frameworks!

# Esta linha ENSINA os comandos do Capacitor para o Podfile.
# Ela precisa vir ANTES de qualquer comando ser usado.
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

target 'App' do
  # Capacitor Pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Seus Plugins
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorDialog', :path => '../../node_modules/@capacitor/dialog'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
end

# Agora que o comando foi ensinado, podemos usá-lo aqui.
post_install do |installer|
  assert_capacitor_swift_version(installer)
end