# Podfile Simplificado ao Máximo para Diagnóstico

platform :ios, '14.0'
use_frameworks!

target 'App' do
  # Pods Essenciais do Capacitor
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Seus Plugins
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorDialog', :path => '../../node_modules/@capacitor/dialog'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
end

# NADA MAIS. O ARQUIVO TERMINA AQUI.
# REMOVEMOS O 'require_relative' E O 'post_install' COMPLETAMENTE.