# Podfile Padrão do Capacitor
platform :ios, '13.0'
use_frameworks!

target 'App' do
  # Capacitor Pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Seus Plugins
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  # Se você não usa Dialog e LocalNotifications, pode remover as duas linhas abaixo
  pod 'CapacitorDialog', :path => '../../node_modules/@capacitor/dialog'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
end

post_install do |installer|
  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
  assert_capacitor_swift_version(installer)
end